backend:
  name: git-gateway
  branch: main # The branch to publish changes to

media_folder: "src/assets/images/uploads" # Where to upload images
public_folder: "/assets/images/uploads" # The public URL for uploaded images

collections:
  - name: "news" # Internal name for the collection
    label: "Aktuelles" # What users see in the CMS UI
    folder: "src/content/news" # Where the news articles will be stored as markdown files
    create: true # Allow users to create new articles
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each article
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "pubDate", widget: "datetime" }
      - { label: "Kurzbeschreibung", name: "description", widget: "string" }
      - { label: "Beitragsbild", name: "heroImage", widget: "image", required: false }
      - { label: "Inhalt des Beitrags", name: "body", widget: "markdown" }